### ISSUE TITLE
The java-version fragment should provide string value in workload.yaml replacements

### ISSUE THREAD

**Issue by trisberg** [vmware-tanzu/application-accelerator-samples#139]
Currently the `workload.yaml` replacement for the build env value ends up as an integer

```
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
```

This should be a string or the Kubernetes API will reject the resource.
